# Generated by Django 6.0.7 on 2026-07-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CVB Store', max_length=120)),
                ('site_tagline', models.CharField(default='Votre boutique moderne pour commander rapidement en ligne.', max_length=255)),
                ('hero_title', models.CharField(default='Commandez vos produits en quelques clics', max_length=150)),
                ('hero_subtitle', models.TextField(default='Une boutique rapide, claire et professionnelle avec panier dynamique, catégories organisées et commande simplifiée.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('about_title', models.CharField(default='A propos de nous', max_length=150)),
                ('about_content', models.TextField(default="Personnalisez cette section depuis l'administration pour présenter votre entreprise, vos valeurs et vos engagements.")),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
