# Generated by Django 6.0.7 on 2026-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('replied', models.BooleanField(default=False, verbose_name='Répondu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('cgv', 'Conditions générales de vente'), ('privacy', 'Politique de confidentialité'), ('legal', 'Mentions légales'), ('delivery', 'Livraison et retours')], unique=True, verbose_name='Type de page')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page statique',
                'verbose_name_plural': 'Pages statiques',
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Image À propos'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Icône du site (format .ico ou .png, 32x32px recommandé)', null=True, upload_to='branding/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Copyright, mentions légales...', verbose_name='Texte du pied de page'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description du site pour les moteurs de recherche', verbose_name='Meta description globale (SEO)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Séparés par des virgules', max_length=255, verbose_name='Mots-clés SEO'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='Exemple: Lun-Ven: 8h-18h, Sam: 9h-14h', max_length=255, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Code hexadécimal ex: #0d6efd', max_length=7, verbose_name='Couleur primaire'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Couleur secondaire'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_content',
            field=models.TextField(default="Personnalisez cette section depuis l'administration pour présenter votre entreprise, vos valeurs et vos engagements.", verbose_name='Contenu À propos'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_title',
            field=models.CharField(default='À propos de nous', max_length=150, verbose_name='Titre À propos'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse physique'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.TextField(default='Une boutique rapide, claire et professionnelle avec panier dynamique, catégories organisées et commande simplifiée.', verbose_name='Sous-titre du hero'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='Commandez vos produits en quelques clics', max_length=150, verbose_name='Titre du hero'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='CVB Store', max_length=120, verbose_name='Nom du site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_tagline',
            field=models.CharField(default='Votre boutique moderne pour commander rapidement en ligne.', max_length=255, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='WhatsApp'),
        ),
    ]
