# Generated by Django 6.0.7 on 2026-07-21 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_faq_pagecontent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code saisi par le client (ex: PROMO10)', max_length=50, unique=True, verbose_name='Code du coupon')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage (%)'), ('fixed', 'Montant fixe (Ar)')], default='percentage', max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Pourcentage (ex: 10 pour 10%) ou montant fixe en Ar', max_digits=10, verbose_name='Valeur de la réduction')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant minimum de commande')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='Utilisations max')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('valid_from', models.DateTimeField(verbose_name='Valable du')),
                ('valid_to', models.DateTimeField(verbose_name='Valable au')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon de réduction',
                'verbose_name_plural': 'Coupons de réduction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemple: Antananarivo, Province, Nationale', max_length=120, verbose_name='Nom de la zone')),
                ('cities', models.TextField(blank=True, help_text='Liste des villes séparées par des virgules', verbose_name='Villes concernées')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de base')),
                ('free_shipping_min', models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum pour livraison gratuite. Laissez vide pour désactiver.', max_digits=10, null=True, verbose_name='Livraison offerte à partir de (Ar)')),
                ('estimated_days', models.CharField(blank=True, help_text='Exemple: 2-3 jours ouvrés', max_length=80, verbose_name='Délai estimé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemple: TVA 20%, TVA réduite 5.5%', max_length=80, verbose_name='Nom')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Exemple: 20 pour 20%', max_digits=5, verbose_name='Taux (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, help_text='Sera appliqué automatiquement aux commandes', verbose_name='Par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Taux de taxe',
                'verbose_name_plural': 'Taux de taxe',
                'ordering': ['-rate'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('order_status', 'Changement de statut commande'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modèle concerné')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Représentation')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activités",
                'ordering': ['-created_at'],
            },
        ),
    ]
