# Generated by Django 6.0.7 on 2026-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coupon_shippingzone_taxrate_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('mvola', 'Mvola'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money')], max_length=20, unique=True, verbose_name='Méthode de paiement')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mode de paiement',
                'verbose_name_plural': 'Modes de paiement',
                'ordering': ['method'],
            },
        ),
    ]
