# Generated by Django 6.0.7 on 2026-07-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, help_text='Nom du titulaire du compte (ex: Jean Rakoto)', max_length=150, verbose_name='Nom du compte'),
        ),
    ]
