# Generated by Django 6.0.7 on 2026-07-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email du demandeur')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolue')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolue le')),
                ('new_password', models.CharField(blank=True, max_length=128, verbose_name='Nouveau mot de passe généré')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_resets_handled', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
                ('user', models.ForeignKey(blank=True, help_text="Rempli automatiquement si l'email correspond à un compte.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Demande de réinitialisation',
                'verbose_name_plural': 'Demandes de réinitialisation',
                'ordering': ['-requested_at'],
            },
        ),
    ]
