# Generated by Django 6.0.7 on 2026-07-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_banner_productimage_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant à ajouter ou soustraire (ex: -500 pour -500 Ar)', max_digits=8, verbose_name='Ajustement de prix'),
        ),
    ]
