# Generated by Django 6.0.7 on 2026-07-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livree'), ('cancelled', 'Annulee')], default='pending', max_length=20),
        ),
    ]
