# Generated by Django 6.0.7 on 2026-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user_orderitem_variant_orderitem_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence de paiement'),
        ),
    ]
