# Generated by Django 6.0.7 on 2026-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Retrait sur place'), ('ship', 'Livraison')], default='pickup', max_length=10, verbose_name='Mode de réception'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zone_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Zone de livraison'),
        ),
    ]
